### ISSUE TITLE
Despawning Issue

### ISSUE THREAD

**Issue by RosemonkeyCT** [capnkirok/animania#317]
Hi,

I appreciate this has been fixed in the newer version but I am still experiencing major despawn issues. Named cows vanish from their pens. Hedgehogs, ferrets and hamsters ON MY SHOULDER just dissapear. Whether I'm moving or standing still... I haven't had the chance to test if those despawn when named or when I sit them down because I can't get them home to name them with a tag and whenever I find them it's by chance so I don't have a nametag on me. But the cows definitely vanish with a nametag. 

I hope there's a way to fix this. Even if there's some code I can add to the config file to stop them despawning altogether? I'd rather be overrun with them than have them vanish when I walk 2 chunks over!

Thanks for taking the time to read this,

Rose x

PS: Running 1.10.2 sorry forgot to mention!

PPS: Checked it out. If I move really short distances before setting it down for a moment and keep moving that way I CAN keep an unnamed hedgehog on my shoulder the whole way home. But it's VERY tedious.

**Comment by capnkirok** [comment]
Thanks for the detail on this issue. I think this is solved, but I can test this scenario.

**Comment by RosemonkeyCT** [comment]
Thanks, I am using the most recent version of the mod with the shoulder riding etc. But the despawning is still an issue for me, at least. If it's something that shows up on logs I can try to recreate it myself and find you a log file but I wasn't sure if it would show up or where to look for it.

**Comment by capnkirok** [comment]
Ok. I "think" this is fixed in 1.10 now. I cannot replicate the above. I did change many things, including entity persistence. Let me know how it goes on 1.3.
