### ISSUE TITLE
[1.12.2] Animals despawning on Server

### ISSUE THREAD

**Issue by yepidoodles** [capnkirok/animania#511]
### Expected Behavior

Player's animals stay when they log out/ server restarts.

### Actual Behavior

Around half of the time, animals despawn. I haven't actually had a chance to play this mod yet, I added it to my newly reset and updated server a few days ago on a community members' request. Several players have reported that animals have been going missing.

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft: 1.12.2
Animania: 1.4.3
Forge: 14.23.1.2587
SpongeForge: 2555-7.1.0-BETA-2831

**Comment by capnkirok** [comment]
Hey @yepidoodles  -

This is directly related to #488 . In the current version, I implemented spawn limits which actually check for extra entities at log out / restarts (and at other times.) In the next version (1.4.5), there are no spawn limits as overspawning is no longer an issue, so it will go away.

In the meantime, there has been some success keeping animals if you give them custom names. Update should be out next weekend.

**Comment by yepidoodles** [comment]
I'm still getting some animals, mostly pets/ name tagged animals despawning.

Updated versions:
Minecraft: 1.12.2
Animania: 1.4.4
Forge: 14.23.1.2594
SpongeForge: 2586-7.1.0-BETA-2862
